[Include]
Include=%D/mkosi.common.conf
        %D/mkosi.obs.conf

[Output]
Format=disk
RepartDirectories=%D/mkosi.repart
ImageId=microos-rpi5
Output=%i_%v_%a
CompressOutput=no
ManifestFormat=json
SplitArtifacts=uki,partitions,roothash

[Content]
ExtraTrees=%D/mkosi.extra
Bootable=yes
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
UnifiedKernelImageFormat=%i_%v_%a
Ssh=yes
SELinuxRelabel=yes
FinalizeScripts=
    %D/mkosi.finalize.chroot
    %D/mkosi.finalize
PostOutputScripts=%D/mkosi.postoutput
KernelCommandLine=
    root=gpt-auto
    rootfstype=erofs
    ro
    systemd.volatile=overlay
    systemd.show_status=yes
    console=tty0
    console=ttyAMA10,115200n8
    earlycon=pl011,0x107d001000,115200n8
    security=selinux
    selinux=1
    enforcing=0
    systemd.mount-extra=/dev/disk/by-label/STATE:/.state:btrfs:rw,nodev,nosuid,x-systemd.growfs
    systemd.mount-extra=/.state/home:/home:none:bind,rw,nodev,nosuid,noexec
    systemd.mount-extra=/.state/var-log:/var/log:none:bind,rw,nodev,nosuid,noexec

[Validation]
SecureBootAutoEnroll=no
Verity=defer
Checksum=yes
