[Content]
CleanPackageMetadata=yes
WithDocs=no
WithRecommends=no
KernelModulesInitrd=yes
KernelInitrdModules=
    bcm2835-dma
    dm-verity
    erofs
    mmc_block
    overlay
    pcie-brcmstb
    pinctrl-brcmstb-bcm2712
    gpio-brcmstb
    fixed
    gpio-regulator
    sdhci-brcmstb
    sdhci-iproc
Packages=
    aaa_base
    bash
    bcm43xx-firmware
    btrfsprogs
    ca-certificates
    ca-certificates-mozilla
    coreutils
    cryptsetup
    device-mapper
    dracut
    erofs-utils
    gpg2
    jeos-firstboot
    kernel-default
    kernel-firmware-all
    less
    MicroOS-release
    NetworkManager
    openssh
    patterns-base-hardware
    patterns-microos-basesystem
    patterns-microos-base-zypper
    patterns-microos-defaults
    patterns-microos-selinux
    raspberrypi-firmware
    raspberrypi-firmware-config
    raspberrypi-firmware-dt
    systemd
    systemd-boot
    systemd-experimental
    timezone
    u-boot-rpiarm64
    udev
    util-linux
    wireless-regdb
    wireless-tools
    wpa_supplicant
    zypp-excludedocs
    zypp-no-multiversion
    zypp-no-recommends

RemovePackages=
    read-only-root-fs
    sdbootutil
    snapper
    transactional-update
