# needssslcertforbuild

[Config]
MinimumVersion=27
Dependencies=
    RaspberryPi
    ContainerHost-RaspberryPi

[Distribution]
Distribution=opensuse
Release=tumbleweed
Architecture=arm64

[Output]
Format=none
OutputDirectory=mkosi.output

[Build]
Incremental=yes
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.pkgcache
MakeScriptsExecutable=yes

[Content]
# OBS resolves the package union before evaluating subimages. Actual image
# contents are selected by the subimages.
Bootable=no
FinalizeScripts=
PostOutputScripts=
Packages=
    aaa_base
    bash
    bcm43xx-firmware
    ca-certificates-mozilla
    coreutils
    cryptsetup
    device-mapper
    dracut
    e2fsprogs
    erofs-utils
    gpg2
    jeos-firstboot
    kernel-default
    kernel-firmware-all
    MicroOS-release
    NetworkManager
    openssh
    patterns-base-hardware
    patterns-containers-container_runtime
    patterns-microos-basesystem
    patterns-microos-base-zypper
    patterns-microos-defaults
    patterns-microos-selinux
    raspberrypi-firmware
    raspberrypi-firmware-config
    raspberrypi-firmware-dt
    systemd
    systemd-boot
    systemd-experimental
    u-boot-rpiarm64
    util-linux
    wireless-regdb
    wireless-tools
    wpa_supplicant
    xfsprogs
    zypp-excludedocs
    zypp-no-multiversion
    zypp-no-recommends
