# needssslcertforbuild

[Config]
MinimumVersion=27
Dependencies=
    RaspberryPi
    ContainerHost-RaspberryPi

[Distribution]
Distribution=opensuse
Release=tumbleweed
Architecture=arm64

[Output]
Format=none
OutputDirectory=mkosi.output

[Build]
SandboxTrees=%D/mkosi.scripts:/usr/lib/extkit-build
Incremental=yes
CacheDirectory=mkosi.cache
PackageCacheDirectory=mkosi.pkgcache
MakeScriptsExecutable=yes

[Content]
# OBS resolves the package union before evaluating subimages. Actual image
# contents are selected by the subimages.
Bootable=no
FinalizeScripts=
PostOutputScripts=
Packages=
    aaa_base
    avahi
    avahi-utils
    bash
    bcm43xx-firmware
    btrfsprogs
    ca-certificates
    ca-certificates-mozilla
    coreutils
    cryptsetup
    device-mapper
    dosfstools
    e2fsprogs
    erofs-utils
    glibc-locale
    gpg2
    jeos-firstboot
    kernel-default
    kernel-firmware-all
    less
    MicroOS-release
    mtools
    NetworkManager
    openssh
    openssl
    patterns-base-hardware
    patterns-containers-container_runtime
    patterns-microos-basesystem
    patterns-microos-defaults
    patterns-microos-selinux
    python3-base
    raspberrypi-firmware
    raspberrypi-firmware-config
    raspberrypi-firmware-dt
    systemd
    systemd-boot
    systemd-container
    systemd-experimental
    timezone
    u-boot-rpiarm64
    udev
    util-linux
    wireless-regdb
    wireless-tools
    wpa_supplicant
    xfsprogs
    NetworkManager-lang
    avahi-lang
    bash-lang
    coreutils-lang
    cryptsetup-lang
    dialog-lang
    findutils-lang
    glib2-lang
    gpg2-lang
    grep-lang
    policycoreutils-lang
    sed-lang
    systemd-lang
    tar-lang
    util-linux-lang
