[Content]
CleanPackageMetadata=yes
WithDocs=no
WithRecommends=no
Packages=
    aaa_base
    bash
    bcm43xx-firmware
    btrfsprogs
    ca-certificates
    ca-certificates-mozilla
    coreutils
    cryptsetup
    device-mapper
    dracut
    erofs-utils
    kernel-default
    kernel-firmware-all
    less
    NetworkManager
    openssh
    patterns-base-hardware
    patterns-microos-basesystem
    patterns-microos-base-zypper
    patterns-microos-defaults
    patterns-microos-selinux
    raspberrypi-firmware
    raspberrypi-firmware-config
    raspberrypi-firmware-dt
    systemd
    systemd-boot
    timezone
    u-boot-rpiarm64
    udev
    util-linux
    wireless-regdb
    wireless-tools
    wpa_supplicant
    zypp-excludedocs
    zypp-no-multiversion
    zypp-no-recommends

RemovePackages=
    jeos-firstboot
    read-only-root-fs
    sdbootutil
    snapper
    transactional-update
