[Content]
SELinuxRelabel=no
Packages=
    bash
    coreutils
    cryptsetup
    device-mapper
    erofs-utils
    systemd
    udev
    util-linux
KernelModulesInitrd=yes
KernelModulesInitrdInclude=
    bcm2835_dma
    dm_verity
    erofs
    mmc_block
    overlay
    pcie_brcmstb
    sdhci_iproc
