[Match]
PathExists=!/.build.binaries

[Distribution]
RepositoryKeyFetch=yes

[Build]
ToolsTree=default
ToolsTreeDistribution=opensuse
ToolsTreeRelease=tumbleweed
SandboxTrees=%D/mkosi.repositories
ToolsTreeSandboxTrees=%D/mkosi.tools.repositories
ToolsTreePackages=
    desync
    dosfstools
    dtc
    efitools
    mtools
    openssl
    sbsigntools
