[Partition]
Type=esp
Format=vfat
CopyFiles=/boot:/
CopyFiles=/efi:/
# Do not set MountPoint here. Otherwise systemd-repart writes the FAT UUID
# of this build's ESP into the versioned root image, which breaks sysupdates
SizeMinBytes=1G
SizeMaxBytes=1G
FileSystemSectorSize=512
SplitName=-
