[Partition]
Type=linux-generic
Label=STATE
Format=btrfs
CopyFiles=/home:/home
CopyFiles=/var/log:/var-log
MakeDirectories=/home /var-log /extensions /confexts /extkit /extkit/boot-updates
SizeMinBytes=1G
Minimize=guess
Compression=zstd
GrowFileSystem=yes
SplitName=-
