[Paths]
StateDirectory=/.state/extkit
RootDirectory=/
OverlayUpperDirectory=/.overlay/upper
BaseDevice=/dev/mapper/root
BaseFileSystem=erofs
RuntimeDirectory=/run
EnabledSysextDirectory=/var/lib/extensions
EnabledConfextDirectory=/var/lib/confexts

[Build]
ErofsTool=mkfs.erofs
