[Paths]
StateDirectory=/.state/extkit
RootDirectory=/
# UPPERDIR VISIBLE-ROOT-PREFIX
OverlayUpperDirectories=
    /.overlay/upper /
    /run/extensions.mutable/etc /etc
    /run/extensions.mutable/usr /usr
    /run/extensions.mutable/opt /opt
    /run/extensions.mutable/var /var
BaseDevice=/dev/mapper/root
BaseFileSystem=erofs
RuntimeDirectory=/run
EnabledSysextDirectory=/.state/extensions
EnabledConfextDirectory=/.state/confexts
RuntimeSysextDirectory=/run/extensions
RuntimeConfextDirectory=/run/confexts

[Extensions]
# TYPE TOP-LEVEL-PATH [TOP-LEVEL-PATH...]
Kinds=
    sysext /usr /opt /var
    confext /etc
# Paths which must never be staged or included in an extension.
ExcludedTrees=
    /var/log
    /var/lib/extensions
    /var/lib/confexts
    /var/lib/extensions.mutable

[Build]
ErofsTool=mkfs.erofs
ErofsFsckTool=fsck.erofs
