[Paths]
StateDirectory=/.state/extkit
RootDirectory=/
# Each entry is: UPPERDIR VISIBLE-ROOT-PREFIX
OverlayUpperDirectories=
    /.overlay/upper /
    /var/lib/extensions.mutable/etc /etc
BaseDevice=/dev/mapper/root
BaseFileSystem=erofs
RuntimeDirectory=/run
EnabledSysextDirectory=/var/lib/extensions
EnabledConfextDirectory=/var/lib/confexts

[Build]
ErofsTool=mkfs.erofs
